name: Deploy_GitHub_Pages

on:
  push:
    branches:
      - main
    paths:
      - index.html
      - website_data/**
  workflow_run:
    workflows:
      - Fetch_Intune_Settings
    types:
      - completed

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy site content
        run: |
          mkdir public
          cp index.html public/
          if [ -d "website_data" ]; then
            cp -r website_data public/
          else
            echo "Warning: website_data directory not found"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
