name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - index.html
      - intune_settings.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy site content
        run: |
          mkdir public
          cp index.html public/
          cp intune_settings.json public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2