name: Fetch Intune Settings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sunday at 03:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install msal requests

      - name: Run script
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python fetch_intune_settings.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add intune_settings.json
          git commit -m "Update Intune settings JSON" || echo "No changes"
          git push